@BASE_URL_LOCALHOST = http://localhost:3000
@BASE_URL = {{BASE_URL_LOCALHOST}}
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTAwODAwNTEsImp0aSI6IntcImlkXCI6XCJNZW1iZXItMjQwMzEwMTM0NTIxXCIsXCJ1c2VybmFtZVwiOlwiZmltYWFhXCIsXCJmdWxsbmFtZVwiOlwiRlwiLFwibWVtYmVyX3R5cGVcIjpcImNsaWVudFwiLFwiaXNfc3VzcGVuZFwiOmZhbHNlLFwiY3JlYXRlZF9hdFwiOlwiMjAyNC0wMy0xMFQwNjo0NToyMS40OTlaXCIsXCJ1cGRhdGVkX2F0XCI6XCIyMDI0LTAzLTEwVDE0OjEzOjExLjM1NzU4NTVaXCIsXCJ0b2tlbl9icm9hZGNhc3RcIjpcIlwiLFwibGFzdF9sb2dpblwiOlwiMDAwMS0wMS0wMVQwMDowMDowMFpcIixcImlkX2RldmljZVwiOlwiXCIsXCJwaG9uZV9udW1iZXJcIjpcIjA4MTIzNDU2Nzg5XCIsXCJlbWFpbFwiOlwidGVzdEB0ZXN0LmNvbVwiLFwicGhvdG9fbWVtYmVyXCI6XCJcIn0ifQ.y5Z9B2LXf9QBGPvZ2hQNOg5uzhTSr3vJ_NREFTq6J3k
@REFRESH_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTAxMDA0ODgsImp0aSI6IntcImlkXCI6XCJNZW1iZXItMjQwMzEwMTM0NTIxXCIsXCJpZF9kZXZpY2VcIjpcIndlYlwifSJ9.cGR7iv-zOD8tRSJzHBkLRpjdveKVYxaPBstp4WM6EWk

### Ping
GET {{BASE_URL}}/ping
Content-Type: application/json


###---------AUTHORIZATION----------###
@AUTH_URL = /api/v1/auth
### LOGIN AUTH
POST {{BASE_URL}}{{AUTH_URL}}/login
Content-Type: application/json

{
  "username": "fimaaa",
  "password":"123456789",
  "token_broadcast":"",
  "id_device":"web"
}

### REFRESH AUTH
POST {{BASE_URL}}{{AUTH_URL}}/refresh
Content-Type: application/json
Authorization: Bearer {{REFRESH_TOKEN}}

{
    "user":"id"
}

###----------MEMBER----------###

### CREATE MEMBER
@MEMBER_URL = /api/v1/member
POST {{BASE_URL}}{{MEMBER_URL}}/create
Content-Type: application/json

{
  "username": "fimaaa",
  "fullname": "F",
  "password":"123456789",
  "member_type":"client",
  "phone_number":"08123456789",
  "email": "test@test.com",
  "photo_member":""
}

### GET ALL MEMBER
GET {{BASE_URL}}{{MEMBER_URL}}?page=1&size=5&username=qra 
Content-Type: application/json

{
  
}